# Generated by Django 3.2.6 on 2021-08-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Pertence ao Funcionário'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
