# Generated by Django 3.2.6 on 2021-08-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user'),
        ('document', '0002_auto_20210805_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Pertence ao Funcionário'),
            preserve_default=False,
        ),
    ]
