# Generated by Django 3.2.6 on 2021-08-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210805_2251'),
        ('overtime_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Funcionário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='motive',
            field=models.CharField(max_length=100, verbose_name='Motivo'),
        ),
    ]
